import type { Circle } from "./types";

export const circles: Circle[] = [
  // ── 運動部 ──
  {
    id: "1",
    name: "サッカー部",
    type: "部活",
    category: "運動系",
    campus: "多摩",
    description: "初心者も経験者も大歓迎！関東リーグ出場を目指して楽しく活動しています。",
    activitySchedule: "毎週 火・木・土 17:00〜19:00",
    events: [
      { date: "2026-04-07", time: "12:00〜13:00", location: "中庭", description: "ランチ説明会" },
      { date: "2026-04-09", time: "17:00〜19:00", location: "第2グラウンド", description: "体験練習会" },
      { date: "2026-04-12", time: "14:00〜16:00", location: "第2グラウンド", description: "ミニゲーム大会" },
    ],
    fee: "月額 ¥2,000",
    memberCount: "約50名",
    belongings: "運動できる服装・シューズ・タオル・飲み物",
    lineAddUrl: "https://line.me/R/ti/p/example1",
    applyUrl: "https://forms.gle/example1",
    sns: { x: "https://x.com/example", instagram: "https://instagram.com/example" },
  },
  {
    id: "2",
    name: "テニスサークル VOLLEY",
    type: "サークル",
    category: "運動系",
    campus: "多摩",
    description: "ゆるく楽しくがモットー！初心者8割。合宿やBBQなどイベント盛りだくさん。",
    activitySchedule: "毎週 水・金 16:00〜18:00",
    events: [
      { date: "2026-04-08", time: "16:00〜18:00", location: "テニスコート", description: "体験会" },
      { date: "2026-04-11", time: "16:00〜18:00", location: "テニスコート", description: "初心者レッスン" },
      { date: "2026-04-13", time: "18:30〜", location: "多摩駅前", description: "新歓コンパ" },
    ],
    fee: "半期 ¥5,000",
    memberCount: "約80名",
    belongings: "動きやすい服装（ラケット貸出あり）",
    featured: true,
    lineAddUrl: "https://line.me/R/ti/p/example2",
    applyUrl: "https://forms.gle/example2",
    sns: { instagram: "https://instagram.com/example" },
  },
  {
    id: "3",
    name: "バスケットボール同好会",
    type: "サークル",
    category: "運動系",
    campus: "両方",
    description: "多摩と後楽園の両キャンパスで活動！試合も交流も楽しめるサークル。",
    activitySchedule: "水 18:00〜20:00（多摩）/ 金 19:00〜21:00（後楽園）",
    events: [
      { date: "2026-04-07", time: "18:00〜20:00", location: "多摩体育館", description: "体験会（多摩）" },
      { date: "2026-04-09", time: "19:00〜21:00", location: "後楽園体育館", description: "体験会（後楽園）" },
    ],
    fee: "月額 ¥1,000",
    memberCount: "約45名",
    belongings: "体育館シューズ・動きやすい服装",
    applyUrl: "https://forms.gle/example3",
    sns: { instagram: "https://instagram.com/example" },
  },
  {
    id: "4",
    name: "ダンスサークル BEAT",
    type: "サークル",
    category: "運動系",
    campus: "多摩",
    description: "HipHop・K-POP・Jazzなどジャンル自由！学祭のステージが最高に盛り上がる。",
    activitySchedule: "毎週 火・木 17:00〜19:00",
    events: [
      { date: "2026-04-08", time: "17:00〜18:30", location: "学生会館2F", description: "ダンス体験会" },
      { date: "2026-04-10", time: "17:00〜18:30", location: "学生会館2F", description: "初心者クラス" },
      { date: "2026-04-13", time: "18:30〜", location: "多摩駅前", description: "新歓飲み会" },
    ],
    fee: "月額 ¥1,500",
    memberCount: "約70名",
    belongings: "動きやすい服装・室内シューズ・タオル",
    notes: "ダンス未経験者が半数以上！",
    featured: true,
    lineAddUrl: "https://line.me/R/ti/p/example4",
    applyUrl: "https://forms.gle/example4",
    sns: { instagram: "https://instagram.com/example", x: "https://x.com/example" },
  },
  {
    id: "5",
    name: "バドミントンサークル",
    type: "サークル",
    category: "運動系",
    campus: "多摩",
    description: "週2回のんびり活動。初心者も経験者も楽しめる雰囲気が自慢です！",
    activitySchedule: "毎週 月・水 18:00〜20:00",
    events: [
      { date: "2026-04-07", time: "18:00〜20:00", location: "第1体育館", description: "体験会" },
      { date: "2026-04-09", time: "18:00〜20:00", location: "第1体育館", description: "練習体験" },
    ],
    fee: "月額 ¥1,000",
    memberCount: "約35名",
    belongings: "体育館シューズ（ラケット貸出あり）",
    applyUrl: "https://forms.gle/example5",
    sns: { instagram: "https://instagram.com/example" },
  },
  {
    id: "6",
    name: "フットサルサークル",
    type: "サークル",
    category: "運動系",
    campus: "後楽園",
    description: "後楽園キャンパス中心に活動。理工学部の仲間と汗を流そう！",
    activitySchedule: "毎週 火・金 19:00〜21:00",
    events: [
      { date: "2026-04-08", time: "19:00〜21:00", location: "後楽園グラウンド", description: "体験会" },
      { date: "2026-04-11", time: "19:00〜21:00", location: "後楽園グラウンド", description: "ミニゲーム" },
    ],
    fee: "月額 ¥1,500",
    memberCount: "約30名",
    belongings: "運動できる服装・シューズ",
    applyUrl: "https://forms.gle/example6",
    sns: { x: "https://x.com/example" },
  },
  {
    id: "7",
    name: "水泳部",
    type: "部活",
    category: "運動系",
    campus: "多摩",
    description: "本格的に泳ぎたい人向け。インカレ出場を目指して週4で練習中。",
    activitySchedule: "毎週 月・水・木・土 7:00〜9:00",
    events: [
      { date: "2026-04-10", time: "12:00〜13:00", location: "学食前", description: "説明会" },
      { date: "2026-04-12", time: "8:00〜10:00", location: "プール", description: "体験練習" },
    ],
    fee: "月額 ¥3,000",
    memberCount: "約25名",
    belongings: "水着・ゴーグル・タオル",
    notes: "泳力不問。マネージャーも募集中！",
    applyUrl: "https://forms.gle/example7",
    sns: { instagram: "https://instagram.com/example" },
  },
  // ── 文化部 ──
  {
    id: "8",
    name: "軽音楽部",
    type: "部活",
    category: "文化系",
    campus: "多摩",
    description: "バンドを組んでライブに出よう！年4回の定期ライブと学祭ステージが活動の柱。",
    activitySchedule: "月〜金 放課後（自主練）/ 土曜 合同練習",
    events: [
      { date: "2026-04-07", time: "12:10〜12:50", location: "学生会館B1", description: "ミニライブ" },
      { date: "2026-04-10", time: "17:00〜19:00", location: "学生会館B1", description: "楽器体験会" },
      { date: "2026-04-12", time: "13:00〜17:00", location: "学生会館B1", description: "バンド体験Day" },
    ],
    fee: "月額 ¥1,500",
    memberCount: "約60名",
    belongings: "なし（楽器は部室にあります）",
    notes: "楽器未経験でもOK！先輩が教えます",
    featured: true,
    lineAddUrl: "https://line.me/R/ti/p/example8",
    applyUrl: "https://forms.gle/example8",
    sns: { x: "https://x.com/example", instagram: "https://instagram.com/example" },
  },
  {
    id: "9",
    name: "プログラミング研究会",
    type: "サークル",
    category: "文化系",
    campus: "後楽園",
    description: "Webアプリ・ゲーム・AI、作りたいものを作る！ハッカソンにも積極参加。",
    activitySchedule: "毎週 金曜 18:00〜20:00",
    events: [
      { date: "2026-04-11", time: "18:00〜19:30", location: "5号館3F", description: "活動紹介&デモ" },
    ],
    fee: "年額 ¥3,000",
    memberCount: "約30名",
    belongings: "ノートPC（あれば）",
    notes: "文系・プログラミング未経験も歓迎",
    applyUrl: "https://forms.gle/example9",
    sns: { x: "https://x.com/example" },
  },
  {
    id: "10",
    name: "写真部",
    type: "部活",
    category: "文化系",
    campus: "多摩",
    description: "カメラ初心者OK！スマホ撮影でも参加できます。月1回の撮影会と学祭での写真展。",
    activitySchedule: "不定期（月2回程度）",
    events: [
      { date: "2026-04-12", time: "10:00〜12:00", location: "多摩キャンパス正門集合", description: "お花見撮影会" },
    ],
    fee: "年額 ¥2,000",
    memberCount: "約25名",
    belongings: "カメラまたはスマホ",
    applyUrl: "https://forms.gle/example10",
    sns: { instagram: "https://instagram.com/example" },
  },
  {
    id: "11",
    name: "国際交流サークル Globe",
    type: "サークル",
    category: "文化系",
    campus: "両方",
    description: "留学生との交流イベントや英会話セッション。海外に興味がある人集まれ！",
    activitySchedule: "毎週 木曜 16:00〜17:30",
    events: [
      { date: "2026-04-09", time: "16:00〜17:30", location: "国際センター", description: "Welcome Party" },
      { date: "2026-04-12", time: "14:00〜16:00", location: "国際センター", description: "留学生交流会" },
    ],
    fee: "年額 ¥1,000",
    memberCount: "約35名",
    belongings: "なし",
    notes: "英語が苦手でも全然OK！日本語メインで活動",
    applyUrl: "https://forms.gle/example11",
    sns: { instagram: "https://instagram.com/example" },
  },
  {
    id: "12",
    name: "映画研究会",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "映画鑑賞会から自主制作まで。映画好きが集まるゆるいサークルです。",
    activitySchedule: "毎週 水曜 18:00〜20:30",
    events: [
      { date: "2026-04-08", time: "18:00〜20:30", location: "3号館視聴覚室", description: "鑑賞会&トーク" },
      { date: "2026-04-13", time: "13:00〜15:00", location: "3号館視聴覚室", description: "自主制作上映会" },
    ],
    fee: "半期 ¥2,000",
    memberCount: "約20名",
    belongings: "なし",
    applyUrl: "https://forms.gle/example12",
    sns: { x: "https://x.com/example", instagram: "https://instagram.com/example" },
  },
  {
    id: "13",
    name: "ボランティアサークル HAND",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "地域の清掃活動や子ども食堂のお手伝いなど。誰かの役に立ちたい人へ。",
    activitySchedule: "隔週 土曜 10:00〜15:00",
    events: [
      { date: "2026-04-08", time: "12:00〜13:00", location: "中庭", description: "活動紹介ブース" },
      { date: "2026-04-12", time: "10:00〜15:00", location: "多摩市内", description: "活動体験" },
    ],
    fee: "なし（無料）",
    memberCount: "約40名",
    belongings: "動きやすい服装",
    applyUrl: "https://forms.gle/example13",
    sns: { instagram: "https://instagram.com/example" },
  },
  {
    id: "14",
    name: "アカペラサークル Voice",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "声だけで音楽を作る！初心者大歓迎。学祭やストリートライブで活躍中。",
    activitySchedule: "毎週 月・木 17:00〜19:00",
    events: [
      { date: "2026-04-07", time: "17:00〜18:00", location: "学生会館3F", description: "ミニコンサート" },
      { date: "2026-04-10", time: "17:00〜19:00", location: "学生会館3F", description: "歌ってみよう会" },
    ],
    fee: "月額 ¥1,000",
    memberCount: "約30名",
    belongings: "なし",
    notes: "歌に自信がなくてもOK！パート指導あり",
    applyUrl: "https://forms.gle/example14",
    sns: { instagram: "https://instagram.com/example" },
  },
  {
    id: "15",
    name: "料理研究会",
    type: "サークル",
    category: "文化系",
    campus: "後楽園",
    description: "みんなで作って食べる！月2回の調理実習と食べ歩きイベント。",
    activitySchedule: "隔週 土曜 11:00〜14:00",
    events: [
      { date: "2026-04-11", time: "18:00〜19:00", location: "後楽園 学生ラウンジ", description: "説明会&試食会" },
    ],
    fee: "月額 ¥2,000（材料費込み）",
    memberCount: "約20名",
    belongings: "エプロン（なくてもOK）",
    applyUrl: "https://forms.gle/example15",
    sns: { instagram: "https://instagram.com/example" },
  },
];
