import type { Circle } from "./types";

export const circles: Circle[] = [
  // ══════════════════════════════════════
  //  運動系
  // ══════════════════════════════════════
  {
    id: "s01",
    name: "BEATS",
    type: "サークル",
    category: "運動系",
    campus: "多摩",
    description: "バレーボール中心のオールラウンドサークル。BBQ・ハロウィン・クリスマスパーティー等イベント盛りだくさん。",
    activitySchedule: "通年（月1〜2回イベント）",
    fee: "¥3,000/年",
    memberCount: "約100名",
    genderRatio: "男6:女4",
    multiClubOk: true,
    belongings: "運動できる服装・室内シューズ",
    notes: "初心者が8割！バレー未経験でも全然大丈夫です。まずは気軽に体験来てね！",
    events: [
      { date: "2026-04-05", time: "14:00〜16:00", location: "第1体育館", description: "体験バレー会" },
      { date: "2026-04-08", time: "17:00〜19:00", location: "第1体育館", description: "新歓バレー+自己紹介" },
      { date: "2026-04-12", time: "13:00〜17:00", location: "多摩キャンパス集合", description: "新歓BBQ" },
    ],
    tags: ["初心者歓迎", "大人数", "飲み会あり", "イベント多め"],
    lineAddUrl: "https://line.me/R/ti/p/example-beats",
    applyUrl: "https://forms.gle/example",
    sns: { instagram: "https://instagram.com/beats_chuo", x: "https://x.com/beats_chuo" },
  },
  {
    id: "s02",
    name: "INDYS",
    type: "サークル",
    category: "運動系",
    campus: "多摩",
    description: "中大唯一のインカレフットサルサークル。月1で活動、ONE DAY大会も開催。",
    activitySchedule: "月1回程度",
    fee: "¥8,000/年",
    genderRatio: "男8:女2",
    notes: "他大の人とも仲良くなれます！フットサル初心者もOK。",
    events: [
      { date: "2026-04-06", time: "10:00〜12:00", location: "第2グラウンド", description: "体験フットサル" },
      { date: "2026-04-13", time: "10:00〜12:00", location: "第2グラウンド", description: "新歓ミニ大会" },
    ],
    tags: ["週1〜2", "インカレ"],
    lineAddUrl: "https://line.me/R/ti/p/example-indys",
    sns: { instagram: "https://instagram.com/indys_chuo" },
  },
  {
    id: "s03",
    name: "FC.Brooklyn",
    type: "サークル",
    category: "運動系",
    campus: "多摩",
    description: "FFCカレッジリーグ1部所属の競技フットサルサークル。中大唯一の競技系。",
    activitySchedule: "通年（大会・練習）",
    fee: "約¥8,000/年",
    memberCount: "約110名",
    genderRatio: "男9:女1",
    belongings: "スパイク・すね当て（貸出あり）",
    notes: "ガチでやりたい人向け。1部リーグで一緒に戦おう！",
    events: [
      { date: "2026-04-05", time: "16:00〜18:00", location: "第2グラウンド", description: "公開練習" },
      { date: "2026-04-10", time: "16:00〜18:00", location: "第2グラウンド", description: "体験練習会" },
    ],
    tags: ["経験者向け", "大人数"],
    lineAddUrl: "https://line.me/R/ti/p/example-brooklyn",
    sns: { x: "https://x.com/fc_brooklyn_chuo" },
  },
  {
    id: "s04",
    name: "Spectators",
    type: "サークル",
    category: "運動系",
    campus: "多摩",
    description: "サッカー「観戦」サークル。観て・語って・楽しむ新しい形のサッカーサークル。",
    activitySchedule: "試合日に合わせて不定期",
    fee: "¥2,000/年",
    memberCount: "約47名",
    genderRatio: "男7:女3",
    notes: "サッカー詳しくなくても全然OK！推しチームを一緒に見つけよう。",
    events: [
      { date: "2026-04-07", time: "18:30〜21:00", location: "学生ラウンジ", description: "新歓観戦パーティー（CL放映）" },
    ],
    tags: ["ゆるめ", "週1〜2"],
    lineAddUrl: "https://line.me/R/ti/p/example-spectators",
    sns: { x: "https://x.com/spectators_chuo" },
  },
  {
    id: "s05",
    name: "中央大学柔道同好会",
    type: "サークル",
    category: "運動系",
    campus: "多摩",
    description: "1973年創部。仲が良く、イベントにも全力投球。初心者歓迎。",
    activitySchedule: "毎週 火・木 18:00〜20:00",
    fee: "¥1,000/年",
    memberCount: "約40名",
    genderRatio: "男7:女3",
    belongings: "柔道着（持っていなければ貸出あり）",
    notes: "大学から始める人が半分以上！体験だけでも歓迎です。",
    events: [
      { date: "2026-04-08", time: "18:00〜20:00", location: "武道場", description: "体験稽古" },
      { date: "2026-04-10", time: "18:00〜20:00", location: "武道場", description: "体験稽古②" },
      { date: "2026-04-15", time: "18:00〜21:00", location: "多摩センター周辺", description: "新歓コンパ" },
    ],
    tags: ["初心者歓迎"],
    lineAddUrl: "https://line.me/R/ti/p/example-judo",
    sns: { instagram: "https://instagram.com/chuo_judo" },
  },
  {
    id: "s06",
    name: "トライアスロンチーム Afro-Q",
    type: "サークル",
    category: "運動系",
    campus: "多摩",
    description: "トライアスロンに挑戦するチーム。スイム・バイク・ランで自分を超えろ！",
    activitySchedule: "毎週 水・土",
    fee: "¥5,000/年",
    memberCount: "約20名",
    genderRatio: "男8:女2",
    belongings: "運動できる服装・水着（体験会のみ不要）",
    notes: "大学からトライアスロンを始める人がほとんど。一緒に挑戦しよう！",
    events: [
      { date: "2026-04-09", time: "16:00〜18:00", location: "多摩キャンパスプール", description: "スイム体験会" },
      { date: "2026-04-16", time: "15:00〜17:00", location: "第2グラウンド", description: "ラン＆バイク体験" },
    ],
    tags: ["経験者向け"],
    lineAddUrl: "https://line.me/R/ti/p/example-afroq",
    sns: { instagram: "https://instagram.com/afroq_chuo" },
  },
  {
    id: "s07",
    name: "陸上競技同好会",
    type: "サークル",
    category: "運動系",
    campus: "多摩",
    description: "経験者も未経験者も歓迎。他サークルとの掛け持ちもOK。",
    activitySchedule: "毎週 火・木 17:00〜19:00",
    fee: "¥6,000/年（1年次）",
    memberCount: "約70名",
    genderRatio: "男5:女5",
    multiClubOk: true,
    belongings: "ランニングシューズ",
    notes: "兼サー率高め！気軽に走りに来てください。",
    events: [
      { date: "2026-04-08", time: "17:00〜19:00", location: "陸上競技場", description: "体験練習会" },
      { date: "2026-04-11", time: "17:00〜19:00", location: "陸上競技場", description: "体験練習会②" },
    ],
    tags: ["初心者歓迎", "大人数", "兼サーOK"],
    lineAddUrl: "https://line.me/R/ti/p/example-rikudo",
    sns: { x: "https://x.com/chuo_rikudo" },
  },
  {
    id: "s08",
    name: "体操愛好会",
    type: "サークル",
    category: "運動系",
    campus: "多摩",
    description: "タンブリング・平行棒・トランポリンなど器械体操を楽しむサークル。",
    activitySchedule: "毎週 月・水 18:00〜20:00",
    fee: "¥1,000/年（新入生¥500）",
    memberCount: "約34名",
    genderRatio: "男4:女6",
    belongings: "動きやすい服装（裸足でOK）",
    notes: "体操経験ゼロの人がほとんど。トランポリン楽しいよ！",
    events: [
      { date: "2026-04-07", time: "18:00〜20:00", location: "第2体育館", description: "トランポリン体験会" },
      { date: "2026-04-14", time: "18:00〜20:00", location: "第2体育館", description: "マット＆平行棒体験" },
    ],
    tags: ["初心者歓迎"],
    lineAddUrl: "https://line.me/R/ti/p/example-taiso",
    sns: { instagram: "https://instagram.com/chuo_taiso" },
  },
  {
    id: "s09",
    name: "ROSENBERG山の会",
    type: "サークル",
    category: "運動系",
    campus: "多摩",
    description: "軽い・安全・楽しい登山がモットー。月1回の登山旅行。",
    activitySchedule: "月1回（登山）",
    fee: "¥3,000（入会金のみ）",
    memberCount: "約25名",
    genderRatio: "男5:女5",
    belongings: "歩きやすい靴・リュック（体験会は高尾山なので普通の靴でOK）",
    notes: "登山初心者でも安心。高尾山から始めて、夏には北アルプスへ！",
    events: [
      { date: "2026-04-12", time: "08:00〜15:00", location: "高尾山口駅集合", description: "新歓ハイキング（高尾山）" },
    ],
    tags: ["ゆるめ", "週1〜2", "少人数"],
    lineAddUrl: "https://line.me/R/ti/p/example-rosenberg",
    sns: { instagram: "https://instagram.com/rosenberg_chuo" },
  },
  {
    id: "s10",
    name: "居合道部",
    type: "部活",
    category: "運動系",
    campus: "多摩",
    description: "日本刀の武道。師範への礼節を重んじ、全日本大会を目指す。",
    activitySchedule: "毎週 月・水・金 17:00〜19:00",
    fee: "¥15,000/年",
    memberCount: "約28名",
    genderRatio: "男6:女4",
    belongings: "ジャージ（刀・道着は貸出あり）",
    notes: "全員大学から始めています。日本刀を扱えるのはここだけ！",
    events: [
      { date: "2026-04-07", time: "17:00〜19:00", location: "武道場", description: "居合道体験（刀に触れます）" },
      { date: "2026-04-11", time: "17:00〜19:00", location: "武道場", description: "体験稽古②" },
      { date: "2026-04-18", time: "18:00〜20:00", location: "多摩センター周辺", description: "新歓食事会" },
    ],
    tags: ["少人数"],
    lineAddUrl: "https://line.me/R/ti/p/example-iaido",
    sns: { x: "https://x.com/chuo_iaido" },
  },
  {
    id: "s11",
    name: "弓道部",
    type: "部活",
    category: "運動系",
    campus: "多摩",
    description: "日本の伝統武道。全国大会出場を目標に真剣な稽古と楽しい練習を両立。",
    activitySchedule: "要確認",
    fee: "¥24,000/年",
    memberCount: "約19名",
    events: [],
    tags: ["少人数"],
    sns: {},
  },
  {
    id: "s12",
    name: "ボート部",
    type: "部活",
    category: "運動系",
    campus: "多摩",
    description: "「日本一」「関東制覇」を目標に活動。部費無料。",
    activitySchedule: "要確認",
    fee: "無料",
    memberCount: "約37名",
    events: [],
    tags: ["経験者向け", "無料"],
    sns: {},
  },
  {
    id: "s13",
    name: "応援団チアリーディング部",
    type: "部活",
    category: "運動系",
    campus: "多摩",
    description: "大学スポーツの応援とチアリーディング大会出場。",
    activitySchedule: "要確認",
    fee: "¥100,000/年",
    memberCount: "約35名",
    events: [],
    tags: ["経験者向け"],
    sns: {},
  },
  {
    id: "s14",
    name: "海洋研究部 Stingray",
    type: "部活",
    category: "運動系",
    campus: "多摩",
    description: "伊豆諸島や沖縄でダイビング。自主的な海洋活動。",
    activitySchedule: "合宿中心",
    fee: "¥40,000〜（機材+合宿費）",
    memberCount: "約15名",
    events: [],
    tags: ["少人数"],
    sns: {},
  },
  {
    id: "s15",
    name: "二輪愛好会 CMC",
    type: "サークル",
    category: "運動系",
    campus: "多摩",
    description: "バイクで全国ツーリング。サーキット走行会もあり。",
    activitySchedule: "不定期（ツーリング）",
    fee: "¥10,000/年",
    memberCount: "約14名",
    events: [],
    tags: ["少人数", "週1〜2"],
    sns: {},
  },
  {
    id: "s16",
    name: "中央大学理工庭球部",
    type: "サークル",
    category: "運動系",
    campus: "後楽園",
    description: "理工学部のテニスサークル。地域リーグ参戦中。",
    activitySchedule: "要確認",
    fee: "¥2,000（入会金）",
    memberCount: "約6名",
    events: [],
    tags: ["少人数"],
    sns: {},
  },
  {
    id: "s17",
    name: "ジャズダンスサークル Schön",
    type: "サークル",
    category: "運動系",
    campus: "多摩",
    description: "ジャズダンスを自由な出席率で楽しむ。スタジオレンタルで活動。",
    activitySchedule: "要確認",
    fee: "実費（スタジオ代）",
    memberCount: "約7名",
    events: [],
    tags: ["ゆるめ", "少人数"],
    sns: {},
  },
  {
    id: "s18",
    name: "アメリカンフットボール部",
    type: "部活",
    category: "運動系",
    campus: "多摩",
    description: "中央大学アメリカンフットボール部。",
    activitySchedule: "要確認",
    events: [],
    tags: ["経験者向け"],
    sns: {},
  },
  {
    id: "s19",
    name: "少林寺拳法部",
    type: "部活",
    category: "運動系",
    campus: "多摩",
    description: "少林寺拳法の稽古を通じた心身の鍛錬。",
    activitySchedule: "要確認",
    events: [],
    tags: [],
    sns: {},
  },
  {
    id: "s20",
    name: "中央大学ラクロス部",
    type: "部活",
    category: "運動系",
    campus: "多摩",
    description: "中央大学ラクロス部。",
    activitySchedule: "要確認",
    events: [],
    tags: [],
    sns: {},
  },
  // ══════════════════════════════════════
  //  文化系
  // ══════════════════════════════════════
  {
    id: "c01",
    name: "QUADS",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "完全ノーレートのポーカーサークル。2023年設立。",
    activitySchedule: "毎週 木曜 18:00〜21:00",
    fee: "¥3,000/年",
    memberCount: "約8名",
    genderRatio: "男7:女1",
    notes: "ポーカー未経験OK！ルールから教えます。",
    events: [
      { date: "2026-04-10", time: "18:00〜21:00", location: "学生ラウンジ", description: "ポーカー体験会" },
      { date: "2026-04-17", time: "18:00〜21:00", location: "学生ラウンジ", description: "ポーカー体験会②" },
    ],
    tags: ["少人数"],
    lineAddUrl: "https://line.me/R/ti/p/example-quads",
    sns: { x: "https://x.com/quads_chuo" },
  },
  {
    id: "c02",
    name: "詩友会",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "月例の詩の会を開催。初心者が多く、気軽に参加できる。",
    activitySchedule: "月1回 土曜午後",
    fee: "無料",
    memberCount: "約13名",
    genderRatio: "男4:女6",
    notes: "書いたことなくても大丈夫。読むだけ参加もOKです。",
    events: [
      { date: "2026-04-12", time: "14:00〜16:00", location: "C棟302教室", description: "新歓・詩の会" },
    ],
    tags: ["初心者歓迎", "ゆるめ", "週1〜2", "少人数"],
    lineAddUrl: "https://line.me/R/ti/p/example-shiyukai",
    sns: {},
  },
  {
    id: "c03",
    name: "キリスト者学生会",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "1950年代から続く歴史あるサークル。聖書研究やゴスペル音楽。",
    activitySchedule: "毎週 水曜 12:30〜13:00",
    memberCount: "約16名",
    genderRatio: "男5:女5",
    notes: "信仰の有無は問いません。ランチタイムに気軽にどうぞ。",
    events: [
      { date: "2026-04-09", time: "12:30〜13:00", location: "B棟201教室", description: "ランチタイム聖書カフェ" },
    ],
    tags: ["少人数"],
    sns: { instagram: "https://instagram.com/chuo_ksg" },
  },
  {
    id: "c04",
    name: "中央大学短歌会",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "31音の短歌を詠む。2024年設立の新しいサークル。毎週活動。",
    activitySchedule: "毎週 金曜 16:00〜18:00",
    fee: "無料",
    memberCount: "約9名",
    genderRatio: "男3:女6",
    notes: "短歌を知らなくても全然OK。言葉が好きならそれだけで十分！",
    events: [
      { date: "2026-04-11", time: "16:00〜18:00", location: "C棟205教室", description: "はじめての短歌ワークショップ" },
      { date: "2026-04-18", time: "16:00〜18:00", location: "C棟205教室", description: "歌会体験" },
    ],
    tags: ["初心者歓迎", "無料", "少人数"],
    lineAddUrl: "https://line.me/R/ti/p/example-tanka",
    sns: { x: "https://x.com/chuo_tanka" },
  },
  {
    id: "c05",
    name: "国際交流サークル Tokyo Best",
    type: "サークル",
    category: "文化系",
    campus: "複数",
    description: "外国人と交流できる機会を提供。企業・大学ネットワーキングも。",
    activitySchedule: "月2〜3回",
    fee: "無料",
    memberCount: "約120名",
    genderRatio: "男4:女6",
    multiClubOk: true,
    notes: "英語力は不問！日本語で交流する機会も多いです。",
    events: [
      { date: "2026-04-06", time: "15:00〜17:00", location: "Gスクエア", description: "Welcome Party" },
      { date: "2026-04-13", time: "14:00〜16:00", location: "学生ラウンジ", description: "Language Exchange" },
      { date: "2026-04-20", time: "18:00〜20:00", location: "多摩センター周辺", description: "International Dinner" },
    ],
    tags: ["初心者歓迎", "無料", "大人数", "インカレ"],
    lineAddUrl: "https://line.me/R/ti/p/example-tokyobest",
    sns: { instagram: "https://instagram.com/tokyobest_chuo", x: "https://x.com/tokyobest" },
  },
  {
    id: "c06",
    name: "学生団体RP",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "ミス・ミスター中大コンテストの企画・運営。撮影・編集・広報を担当。",
    activitySchedule: "通年（白門祭前は週3〜4）",
    fee: "¥2,000/年",
    memberCount: "約60名",
    genderRatio: "男3:女7",
    notes: "カメラ・動画編集・SNS運用に興味があればぜひ！スキルは入ってから身につきます。",
    events: [
      { date: "2026-04-09", time: "18:00〜19:30", location: "C棟401教室", description: "新歓説明会" },
      { date: "2026-04-16", time: "18:00〜20:00", location: "Gスクエア", description: "撮影体験ワークショップ" },
    ],
    tags: ["大人数", "イベント多め"],
    lineAddUrl: "https://line.me/R/ti/p/example-rp",
    sns: { instagram: "https://instagram.com/rp_chuo", x: "https://x.com/rp_chuo" },
  },
  {
    id: "c07",
    name: "Sound Life Community",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "1997年設立。様々なジャンルのライブ音楽パフォーマンス。年9回ライブ。",
    activitySchedule: "年9回ライブ + 不定期セッション",
    fee: "¥10,000/年",
    memberCount: "約76名",
    genderRatio: "男6:女4",
    belongings: "楽器（持っていなければ相談OK）",
    notes: "ボーカル・ギター・ベース・ドラム・キーボード、全パート募集中！初心者バンドもあります。",
    events: [
      { date: "2026-04-05", time: "16:00〜19:00", location: "Cスクエア地下スタジオ", description: "新歓ライブ" },
      { date: "2026-04-10", time: "17:00〜19:00", location: "Cスクエア地下スタジオ", description: "楽器体験会" },
      { date: "2026-04-19", time: "16:00〜19:00", location: "Cスクエア地下スタジオ", description: "新歓ライブ②" },
    ],
    tags: ["大人数", "イベント多め"],
    lineAddUrl: "https://line.me/R/ti/p/example-slc",
    sns: { instagram: "https://instagram.com/slc_chuo", x: "https://x.com/slc_chuo" },
  },
  {
    id: "c08",
    name: "中央大学旅サークル SOLACE",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "2022年設立。国内旅行で忘れられない体験を。キャンプ・温泉なども。",
    activitySchedule: "月1回程度",
    fee: "¥1,000/年",
    memberCount: "約70名",
    genderRatio: "男5:女5",
    multiClubOk: true,
    notes: "旅好きが集まるゆるいサークル。行き先はみんなで決めます！",
    events: [
      { date: "2026-04-08", time: "18:00〜19:30", location: "C棟301教室", description: "新歓説明会（旅の写真上映会）" },
      { date: "2026-04-19", time: "09:00〜18:00", location: "多摩センター駅集合", description: "日帰り鎌倉旅行" },
    ],
    tags: ["初心者歓迎", "ゆるめ", "週1〜2", "大人数", "兼サーOK"],
    lineAddUrl: "https://line.me/R/ti/p/example-solace",
    sns: { instagram: "https://instagram.com/solace_chuo" },
  },
  {
    id: "c09",
    name: "児童文学研究会イーハトーヴ",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "児童文学を読む・描く・語り聞かせる。ギャラリー訪問も月1回。",
    activitySchedule: "月1回 土曜午後",
    fee: "無料",
    memberCount: "約25名",
    genderRatio: "男2:女8",
    notes: "絵本や童話が好きな人、集まれ〜！読み聞かせボランティアもやってます。",
    events: [
      { date: "2026-04-12", time: "13:00〜15:00", location: "図書館ラウンジ", description: "絵本カフェ（お茶付き）" },
    ],
    tags: ["ゆるめ", "週1〜2", "無料", "少人数"],
    lineAddUrl: "https://line.me/R/ti/p/example-ihatov",
    sns: { instagram: "https://instagram.com/ihatov_chuo" },
  },
  {
    id: "c10",
    name: "製菓研究会銀月",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "月1回のお菓子作りと調理イベント。白門祭にも出店。",
    activitySchedule: "月1回 日曜",
    fee: "¥1,000（入会金）+ 1回¥300",
    memberCount: "約94名",
    genderRatio: "男2:女8",
    belongings: "エプロン（なくてもOK）",
    notes: "お菓子作り初めてでも大丈夫！みんなで作ると楽しいよ。白門祭のケーキは毎年完売！",
    events: [
      { date: "2026-04-06", time: "13:00〜16:00", location: "調理実習室", description: "新歓お菓子作り体験（シュークリーム）" },
      { date: "2026-04-13", time: "13:00〜16:00", location: "調理実習室", description: "新歓お菓子作り体験②（マカロン）" },
    ],
    tags: ["初心者歓迎", "ゆるめ", "週1〜2", "大人数"],
    lineAddUrl: "https://line.me/R/ti/p/example-gingetsu",
    sns: { instagram: "https://instagram.com/gingetsu_chuo" },
  },
  {
    id: "c11",
    name: "モダンジャズ研究会",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "毎週金曜のジャムセッション中心。BBQ・合宿・クリスマスセッションも。",
    activitySchedule: "毎週 金曜",
    fee: "¥5,000/年",
    memberCount: "約60名",
    events: [],
    tags: ["初心者歓迎", "週1〜2", "大人数", "イベント多め"],
    sns: {},
  },
  {
    id: "c12",
    name: "辞達学会",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "日本最古の文化サークル。ディベート大会への出場と練習。",
    activitySchedule: "要確認",
    fee: "約¥5,000/半期",
    memberCount: "約48名",
    events: [],
    tags: [],
    sns: {},
  },
  {
    id: "c13",
    name: "第二劇研",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "春・秋・卒業公演を中心に演劇を制作。年3回の本公演。",
    activitySchedule: "公演準備期間に集中",
    fee: "公演ごとに徴収",
    memberCount: "約50名",
    events: [],
    tags: ["初心者歓迎", "大人数"],
    sns: {},
  },
  {
    id: "c14",
    name: "探検部",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "山登り・洞窟探検・無人島遠征。関東圏を中心に活動。",
    activitySchedule: "不定期（遠征中心）",
    fee: "無料（遠征費は割り勘）",
    memberCount: "約72名",
    events: [],
    tags: ["初心者歓迎", "無料", "大人数"],
    sns: {},
  },
  {
    id: "c15",
    name: "白門ヘラルド",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "英字新聞の制作。政治・経済・社会・スポーツ・エンタメを英語で執筆。",
    activitySchedule: "要確認",
    fee: "無料",
    memberCount: "約21名",
    events: [],
    tags: ["無料", "少人数"],
    sns: {},
  },
  {
    id: "c16",
    name: "古典ギタークラブ",
    type: "部活",
    category: "文化系",
    campus: "多摩",
    description: "クラシックギターのソロ・デュエット・アンサンブル。定期演奏会あり。",
    activitySchedule: "要確認",
    fee: "¥6,000/年",
    memberCount: "約16名",
    events: [],
    tags: ["初心者歓迎", "少人数"],
    sns: {},
  },
  {
    id: "c17",
    name: "中央大学ポケモンだいすきクラブ",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "ポケモンのゲーム・カードを楽しむサークル。白門祭にも参加。",
    activitySchedule: "要確認",
    fee: "無料",
    events: [],
    tags: ["ゆるめ", "無料"],
    sns: {},
  },
  {
    id: "c18",
    name: "コーヒー同好会",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "月1回のカフェ巡り、コーヒーテイスティング。ゆるい雰囲気が特徴。",
    activitySchedule: "月1回程度",
    fee: "¥3,000/年",
    memberCount: "約30名",
    events: [],
    tags: ["ゆるめ", "週1〜2"],
    sns: {},
  },
  {
    id: "c19",
    name: "寺社巡りサークル",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "関東圏の寺社を巡る。学生目線で歴史を探訪。準公認。",
    activitySchedule: "要確認",
    fee: "¥2,000/年",
    memberCount: "約51名",
    events: [],
    tags: ["ゆるめ", "大人数"],
    sns: {},
  },
  {
    id: "c20",
    name: "C-Habitat",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "国際NGO ハビタット・フォー・ヒューマニティのボランティア活動。国内外で活動。",
    activitySchedule: "要確認",
    fee: "¥500〜1,000/年",
    memberCount: "約60名",
    events: [],
    tags: ["初心者歓迎", "大人数"],
    sns: {},
  },
  {
    id: "c21",
    name: "グリーンバード 多摩・高幡不動チーム",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "NPO法人グリーンバードの清掃ボランティア。多摩センター・高幡不動駅周辺。",
    activitySchedule: "月2回",
    fee: "無料",
    memberCount: "約6名（運営）+ ボランティア20名",
    events: [],
    tags: ["ゆるめ", "無料", "少人数"],
    sns: {},
  },
  {
    id: "c22",
    name: "中央大学アイドルゲーム研究会",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "アイドルマスターシリーズ中心。同人誌販売・会誌発行・カラオケ等。",
    activitySchedule: "週1〜隔週",
    fee: "無料",
    events: [],
    tags: ["ゆるめ", "無料"],
    sns: {},
  },
];
