import type { Circle } from "./types";

export const circles: Circle[] = [
  // ══════════════════════════════════════
  //  運動系
  // ══════════════════════════════════════
  {
    id: "s01",
    name: "BEATS",
    type: "サークル",
    category: "運動系",
    campus: "多摩",
    description: "バレーボール中心のオールラウンドサークル。BBQ・ハロウィン・クリスマスパーティー等イベント盛りだくさん。",
    activitySchedule: "通年（月1〜2回イベント）",
    fee: "¥3,000/年",
    memberCount: "約100名",
    events: [],
    tags: ["初心者歓迎", "大人数", "飲み会あり", "イベント多め"],
    sns: { instagram: "https://instagram.com/example" },
  },
  {
    id: "s02",
    name: "INDYS",
    type: "サークル",
    category: "運動系",
    campus: "多摩",
    description: "中大唯一のインカレフットサルサークル。月1で活動、ONE DAY大会も開催。",
    activitySchedule: "月1回程度",
    fee: "¥8,000/年",
    events: [],
    tags: ["週1〜2", "インカレ"],
    sns: {},
  },
  {
    id: "s03",
    name: "FC.Brooklyn",
    type: "サークル",
    category: "運動系",
    campus: "多摩",
    description: "FFCカレッジリーグ1部所属の競技フットサルサークル。中大唯一の競技系。",
    activitySchedule: "通年（大会・練習）",
    fee: "約¥8,000/年",
    memberCount: "約110名",
    events: [],
    tags: ["経験者向け", "大人数"],
    sns: {},
  },
  {
    id: "s04",
    name: "Spectators",
    type: "サークル",
    category: "運動系",
    campus: "多摩",
    description: "サッカー「観戦」サークル。観て・語って・楽しむ新しい形のサッカーサークル。",
    activitySchedule: "試合日に合わせて不定期",
    fee: "¥2,000/年",
    memberCount: "約47名",
    events: [],
    tags: ["ゆるめ", "週1〜2"],
    sns: {},
  },
  {
    id: "s05",
    name: "中央大学柔道同好会",
    type: "サークル",
    category: "運動系",
    campus: "多摩",
    description: "1973年創部。仲が良く、イベントにも全力投球。初心者歓迎。",
    activitySchedule: "要確認",
    fee: "¥1,000/年",
    memberCount: "約40名",
    events: [],
    tags: ["初心者歓迎"],
    sns: {},
  },
  {
    id: "s06",
    name: "トライアスロンチーム Afro-Q",
    type: "サークル",
    category: "運動系",
    campus: "多摩",
    description: "トライアスロンに挑戦するチーム。",
    activitySchedule: "要確認",
    events: [],
    tags: ["経験者向け"],
    sns: {},
  },
  {
    id: "s07",
    name: "陸上競技同好会",
    type: "サークル",
    category: "運動系",
    campus: "多摩",
    description: "経験者も未経験者も歓迎。他サークルとの掛け持ちもOK。",
    activitySchedule: "要確認",
    fee: "¥6,000/年（1年次）",
    memberCount: "約70名",
    events: [],
    tags: ["初心者歓迎", "大人数", "兼サーOK"],
    sns: {},
  },
  {
    id: "s08",
    name: "体操愛好会",
    type: "サークル",
    category: "運動系",
    campus: "多摩",
    description: "タンブリング・平行棒・トランポリンなど器械体操を楽しむサークル。",
    activitySchedule: "要確認",
    fee: "¥1,000/年（新入生¥500）",
    memberCount: "約34名",
    events: [],
    tags: ["初心者歓迎"],
    sns: {},
  },
  {
    id: "s09",
    name: "ROSENBERG山の会",
    type: "サークル",
    category: "運動系",
    campus: "多摩",
    description: "軽い・安全・楽しい登山がモットー。月1回の登山旅行。",
    activitySchedule: "月1回（登山）",
    fee: "¥3,000（入会金のみ）",
    memberCount: "約25名",
    events: [],
    tags: ["ゆるめ", "週1〜2", "少人数"],
    sns: {},
  },
  {
    id: "s10",
    name: "居合道部",
    type: "部活",
    category: "運動系",
    campus: "多摩",
    description: "日本刀の武道。師範への礼節を重んじ、全日本大会を目指す。",
    activitySchedule: "要確認",
    fee: "¥15,000/年",
    memberCount: "約28名",
    events: [],
    tags: ["少人数"],
    sns: {},
  },
  {
    id: "s11",
    name: "弓道部",
    type: "部活",
    category: "運動系",
    campus: "多摩",
    description: "日本の伝統武道。全国大会出場を目標に真剣な稽古と楽しい練習を両立。",
    activitySchedule: "要確認",
    fee: "¥24,000/年",
    memberCount: "約19名",
    events: [],
    tags: ["少人数"],
    sns: {},
  },
  {
    id: "s12",
    name: "ボート部",
    type: "部活",
    category: "運動系",
    campus: "多摩",
    description: "「日本一」「関東制覇」を目標に活動。部費無料。",
    activitySchedule: "要確認",
    fee: "無料",
    memberCount: "約37名",
    events: [],
    tags: ["経験者向け", "無料"],
    sns: {},
  },
  {
    id: "s13",
    name: "応援団チアリーディング部",
    type: "部活",
    category: "運動系",
    campus: "多摩",
    description: "大学スポーツの応援とチアリーディング大会出場。",
    activitySchedule: "要確認",
    fee: "¥100,000/年",
    memberCount: "約35名",
    events: [],
    tags: ["経験者向け"],
    sns: {},
  },
  {
    id: "s14",
    name: "海洋研究部 Stingray",
    type: "部活",
    category: "運動系",
    campus: "多摩",
    description: "伊豆諸島や沖縄でダイビング。自主的な海洋活動。",
    activitySchedule: "合宿中心",
    fee: "¥40,000〜（機材+合宿費）",
    memberCount: "約15名",
    events: [],
    tags: ["少人数"],
    sns: {},
  },
  {
    id: "s15",
    name: "二輪愛好会 CMC",
    type: "サークル",
    category: "運動系",
    campus: "多摩",
    description: "バイクで全国ツーリング。サーキット走行会もあり。",
    activitySchedule: "不定期（ツーリング）",
    fee: "¥10,000/年",
    memberCount: "約14名",
    events: [],
    tags: ["少人数", "週1〜2"],
    sns: {},
  },
  {
    id: "s16",
    name: "中央大学理工庭球部",
    type: "サークル",
    category: "運動系",
    campus: "後楽園",
    description: "理工学部のテニスサークル。地域リーグ参戦中。",
    activitySchedule: "要確認",
    fee: "¥2,000（入会金）",
    memberCount: "約6名",
    events: [],
    tags: ["少人数"],
    sns: {},
  },
  {
    id: "s17",
    name: "ジャズダンスサークル Schön",
    type: "サークル",
    category: "運動系",
    campus: "多摩",
    description: "ジャズダンスを自由な出席率で楽しむ。スタジオレンタルで活動。",
    activitySchedule: "要確認",
    fee: "実費（スタジオ代）",
    memberCount: "約7名",
    events: [],
    tags: ["ゆるめ", "少人数"],
    sns: {},
  },
  {
    id: "s18",
    name: "アメリカンフットボール部",
    type: "部活",
    category: "運動系",
    campus: "多摩",
    description: "中央大学アメリカンフットボール部。",
    activitySchedule: "要確認",
    events: [],
    tags: ["経験者向け"],
    sns: {},
  },
  {
    id: "s19",
    name: "少林寺拳法部",
    type: "部活",
    category: "運動系",
    campus: "多摩",
    description: "少林寺拳法の稽古を通じた心身の鍛錬。",
    activitySchedule: "要確認",
    events: [],
    tags: [],
    sns: {},
  },
  {
    id: "s20",
    name: "中央大学ラクロス部",
    type: "部活",
    category: "運動系",
    campus: "多摩",
    description: "中央大学ラクロス部。",
    activitySchedule: "要確認",
    events: [],
    tags: [],
    sns: {},
  },
  // ══════════════════════════════════════
  //  文化系
  // ══════════════════════════════════════
  {
    id: "c01",
    name: "QUADS",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "完全ノーレートのポーカーサークル。2023年設立。",
    activitySchedule: "要確認",
    fee: "¥3,000/年",
    memberCount: "約8名",
    events: [],
    tags: ["少人数"],
    sns: {},
  },
  {
    id: "c02",
    name: "詩友会",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "月例の詩の会を開催。初心者が多く、気軽に参加できる。",
    activitySchedule: "月1回",
    memberCount: "約13名",
    events: [],
    tags: ["初心者歓迎", "ゆるめ", "週1〜2", "少人数"],
    sns: {},
  },
  {
    id: "c03",
    name: "キリスト者学生会",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "1950年代から続く歴史あるサークル。聖書研究やゴスペル音楽。",
    activitySchedule: "要確認",
    memberCount: "約16名",
    events: [],
    tags: ["少人数"],
    sns: {},
  },
  {
    id: "c04",
    name: "中央大学短歌会",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "31音の短歌を詠む。2024年設立の新しいサークル。毎週活動。",
    activitySchedule: "毎週",
    fee: "無料",
    memberCount: "約9名",
    events: [],
    tags: ["初心者歓迎", "無料", "少人数"],
    sns: {},
  },
  {
    id: "c05",
    name: "国際交流サークル Tokyo Best",
    type: "サークル",
    category: "文化系",
    campus: "両方",
    description: "外国人と交流できる機会を提供。企業・大学ネットワーキングも。",
    activitySchedule: "要確認",
    fee: "無料",
    memberCount: "約120名",
    events: [],
    tags: ["初心者歓迎", "無料", "大人数"],
    sns: {},
  },
  {
    id: "c06",
    name: "学生団体RP",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "ミス・ミスター中大コンテストの企画・運営。撮影・編集・広報を担当。",
    activitySchedule: "通年",
    fee: "¥2,000/年",
    memberCount: "約60名",
    events: [],
    tags: ["大人数"],
    sns: {},
  },
  {
    id: "c07",
    name: "Sound Life Community",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "1997年設立。様々なジャンルのライブ音楽パフォーマンス。年9回ライブ。",
    activitySchedule: "年9回ライブ + 不定期イベント",
    fee: "¥10,000/年",
    memberCount: "約76名",
    events: [],
    tags: ["大人数"],
    sns: {},
  },
  {
    id: "c08",
    name: "中央大学旅サークル SOLACE",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "2022年設立。国内旅行で忘れられない体験を。キャンプ・温泉なども。",
    activitySchedule: "月1回程度",
    fee: "¥1,000/年",
    memberCount: "約70名",
    events: [],
    tags: ["初心者歓迎", "ゆるめ", "週1〜2", "大人数"],
    sns: {},
  },
  {
    id: "c09",
    name: "児童文学研究会イーハトーヴ",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "児童文学を読む・描く・語り聞かせる。ギャラリー訪問も月1回。",
    activitySchedule: "月1回程度",
    fee: "無料",
    memberCount: "約25名",
    events: [],
    tags: ["ゆるめ", "週1〜2", "無料", "少人数"],
    sns: {},
  },
  {
    id: "c10",
    name: "製菓研究会銀月",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "月1回のお菓子作りと調理イベント。白門祭にも出店。",
    activitySchedule: "月1回",
    fee: "¥1,000（入会金）+ 1回¥300",
    memberCount: "約94名",
    events: [],
    tags: ["初心者歓迎", "ゆるめ", "週1〜2", "大人数"],
    sns: {},
  },
  {
    id: "c11",
    name: "モダンジャズ研究会",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "毎週金曜のジャムセッション中心。BBQ・合宿・クリスマスセッションも。",
    activitySchedule: "毎週 金曜",
    fee: "¥5,000/年",
    memberCount: "約60名",
    events: [],
    tags: ["初心者歓迎", "週1〜2", "大人数", "イベント多め"],
    sns: {},
  },
  {
    id: "c12",
    name: "辞達学会",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "日本最古の文化サークル。ディベート大会への出場と練習。",
    activitySchedule: "要確認",
    fee: "約¥5,000/半期",
    memberCount: "約48名",
    events: [],
    tags: [],
    sns: {},
  },
  {
    id: "c13",
    name: "第二劇研",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "春・秋・卒業公演を中心に演劇を制作。年3回の本公演。",
    activitySchedule: "公演準備期間に集中",
    fee: "公演ごとに徴収",
    memberCount: "約50名",
    events: [],
    tags: ["初心者歓迎", "大人数"],
    sns: {},
  },
  {
    id: "c14",
    name: "探検部",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "山登り・洞窟探検・無人島遠征。関東圏を中心に活動。",
    activitySchedule: "不定期（遠征中心）",
    fee: "無料（遠征費は割り勘）",
    memberCount: "約72名",
    events: [],
    tags: ["初心者歓迎", "無料", "大人数"],
    sns: {},
  },
  {
    id: "c15",
    name: "白門ヘラルド",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "英字新聞の制作。政治・経済・社会・スポーツ・エンタメを英語で執筆。",
    activitySchedule: "要確認",
    fee: "無料",
    memberCount: "約21名",
    events: [],
    tags: ["無料", "少人数"],
    sns: {},
  },
  {
    id: "c16",
    name: "古典ギタークラブ",
    type: "部活",
    category: "文化系",
    campus: "多摩",
    description: "クラシックギターのソロ・デュエット・アンサンブル。定期演奏会あり。",
    activitySchedule: "要確認",
    fee: "¥6,000/年",
    memberCount: "約16名",
    events: [],
    tags: ["初心者歓迎", "少人数"],
    sns: {},
  },
  {
    id: "c17",
    name: "中央大学ポケモンだいすきクラブ",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "ポケモンのゲーム・カードを楽しむサークル。白門祭にも参加。",
    activitySchedule: "要確認",
    fee: "無料",
    events: [],
    tags: ["ゆるめ", "無料"],
    sns: {},
  },
  {
    id: "c18",
    name: "コーヒー同好会",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "月1回のカフェ巡り、コーヒーテイスティング。ゆるい雰囲気が特徴。",
    activitySchedule: "月1回程度",
    fee: "¥3,000/年",
    memberCount: "約30名",
    events: [],
    tags: ["ゆるめ", "週1〜2"],
    sns: {},
  },
  {
    id: "c19",
    name: "寺社巡りサークル",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "関東圏の寺社を巡る。学生目線で歴史を探訪。準公認。",
    activitySchedule: "要確認",
    fee: "¥2,000/年",
    memberCount: "約51名",
    events: [],
    tags: ["ゆるめ", "大人数"],
    sns: {},
  },
  {
    id: "c20",
    name: "C-Habitat",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "国際NGO ハビタット・フォー・ヒューマニティのボランティア活動。国内外で活動。",
    activitySchedule: "要確認",
    fee: "¥500〜1,000/年",
    memberCount: "約60名",
    events: [],
    tags: ["初心者歓迎", "大人数"],
    sns: {},
  },
  {
    id: "c21",
    name: "グリーンバード 多摩・高幡不動チーム",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "NPO法人グリーンバードの清掃ボランティア。多摩センター・高幡不動駅周辺。",
    activitySchedule: "月2回",
    fee: "無料",
    memberCount: "約6名（運営）+ ボランティア20名",
    events: [],
    tags: ["ゆるめ", "無料", "少人数"],
    sns: {},
  },
  {
    id: "c22",
    name: "中央大学アイドルゲーム研究会",
    type: "サークル",
    category: "文化系",
    campus: "多摩",
    description: "アイドルマスターシリーズ中心。同人誌販売・会誌発行・カラオケ等。",
    activitySchedule: "週1〜隔週",
    fee: "無料",
    events: [],
    tags: ["ゆるめ", "無料"],
    sns: {},
  },
];
